apiVersion: v1
data:
  BACKEND_HOST: web:8000
  WORKER_PROCESSES: '1'
  WORKER_CONNECTIONS: '1024'
  KEEPALIVE_TIMEOUT: '65'
  BACKEND_MAX_FAILS: '3'
  BACKEND_MAX_TIMEOUT: 10s
  LOG_STDOUT: 'true'
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
