apiVersion: v1
data:
  {{- with .Values.imageConfigMaps }}
  BACKEND_HOST: {{ .backendHost }}
  WORKER_PROCESSES: '1' # {{ .workerProcesses }}
  WORKER_CONNECTIONS: '1024' # {{ .workerConnections }}
  KEEPALIVE_TIMEOUT: '65' # {{ .keepaliveTimeout }}
  BACKEND_MAX_FAILS: '3' # {{ .backendMaxFails }}
  BACKEND_MAX_TIMEOUT: 10s # {{ .backendMaxTimeout }}
  LOG_STDOUT: "true" # {{ .logStdout }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
