apiVersion: v1
data:
  {{- with .Values.imageConfigMaps }}
  BACKEND_HOST: {{ .backendHost | quote }}
  WORKER_PROCESSES: {{ .workerProcesses | quote }}
  WORKER_CONNECTIONS: {{ .workerConnections | quote }}
  KEEPALIVE_TIMEOUT: {{ .keepaliveTimeout | quote }}
  BACKEND_MAX_FAILS: {{ .backendMaxFails | quote }}
  BACKEND_MAX_TIMEOUT: {{ .backendMaxTimeout }}
  LOG_STDOUT: {{ .logStdout | quote }}
  SERVER_PORT: {{ .Values.service.port }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
