apiVersion: v1
data:
  {{- with .Values.imageConfigMaps }}
  BACKEND_HOST: {{ .backendHost }}
  WORKER_PROCESSES: {{ .workerProcesses }}
  WORKER_CONNECTIONS: {{ .workerConnections }}
  KEEPALIVE_TIMEOUT: {{ .keepaliveTimeout }}
  BACKEND_MAX_FAILS: {{ .backendMaxFails }}
  BACKEND_MAX_TIMEOUT: {{ .backendMaxTimeout }}
  LOG_STDOUT: {{ .logStdout }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
