apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nginx.fullname" . }}-static-{{ .Values.global.appMode }}-nfs-pv
spec:
  storageClassName: static
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /var/lib/jenkins/workspace/Rebs/app/django/static
    server: 49.247.26.88
