apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx.fullname" . }}-static-{{ .Values.global.appMode }}-nfs-pvc
spec:
  storageClassName: {{ include "nginx.fullname" . }}-static-{{ .Values.global.appMode }}
  accessModes:
  {{- range .Values.volumes.staticAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
    {{- if eq .Values.global.appMode "prod" }}
      storage: {{ .Values.volumes.staticPvcStorageProd }}
    {{- else if eq .Values.global.appMode "dev" }}
      storage: {{ .Values.volumes.staticPvcStorageProd }}
    {{- end }}
