apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx.fullname" . }}-static-{{ .Values.global.appMode }}-nfs-pvc
spec:
  storageClassName: static
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
