apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "uwsgi --socket :8000 --module _config.wsgi --py-autoreload 1 --logto /tmp/mylog.log"]
          envFrom:
            - configMapRef:
                name: web-config
            - secretRef:
                name: web-secret
          ports:
            - name: web
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - python
                - --version
          volumeMounts:
            - name: applications
              mountPath: /app/django
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: applications
          persistentVolumeClaim:
            claimName: {{ include "web.fullname" . }}-django-{{ .Values.global.appMode }}-nfs-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:

        {{- toYaml . | nindent 8 }}
      {{- end }}
