apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - bash
            - "-c"
            - |
              if [ ! -d "./media" ]; then mkdir media; chmod -R 755 ./media fi
              python manage.py collectstatic --no-input
              python manage.py makemigrations accounts book board cash company contract docs items notice payment project rebs work
              python manage.py migrate
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/bash" ]
          args: [ "-c", "uwsgi --socket :8000 --module _config.wsgi --py-autoreload 1 --logto /tmp/mylog.log" ]
          envFrom:
            - configMapRef:
                name: {{ include "web.fullname" . }}-config
            - secretRef:
                name: {{ include "web.fullname" . }}-db-auth
          ports:
            - name: web
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: django-source
              mountPath: /app/django
            - name: tz-seoul
              mountPath: /etc/localtime
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: django-source
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ include "web.fullname" . }}-{{ .Values.global.appMode }}-django-pvc
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:

        {{- toYaml . | nindent 8 }}
      {{- end }}
