apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "web.fullname" . }}-django-{{ .Values.global.appMode }}-nfs-pv
spec:
  storageClassName: {{ include "web.fullname" . }}-app
  capacity:
    storage: {{ .Values.volumes.djangoPvStorage }}
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.global.nfsPath }}/app/django
    server: {{ .Values.volumes.nfsServerHost | default "localhost" }}
