apiVersion: v1
kind: PersistentVolume
metadata:
  { { - if eq .Values.global.mode "prod" } }
  name: { { include "web.fullname" . } }-django-prod-nfs-pv
  {{- else if eq .Values.global.mode "dev" }}
  name: { { include "web.fullname" . } }-django-dev-nfs-pv
  {{- end }}
spec:
  storageClassName: app
  capacity:
    storage: { { .Values.volumes.djangoPvStorage } }
  accessModes:
  { { - range .Values.volumes.djangoAccessModes } }
  - { { . } }
  { { - end } }
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/lib/jenkins/workspace/Rebs/app/django
    server: { { .Values.volumes.nfsServerHost | default "localhost" } }
