apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web.fullname" . }}-django-{{ .Values.global.appMode }}-nfs-pvc
spec:
  storageClassName: app
  accessModes:
  {{- range .Values.volumes.djangoAccessModes }}
  - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.djangoPvcStorage }}
