apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web.fullname" . }}-django-{{ .Values.global.appMode }}-nfs-pvc
spec:
  storageClassName: {{ include "web.fullname" . }}-app
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.djangoPvcStorage }}
