# Default values for Rebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  appMode: prod

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

nginx:
  ingress:
    hosts:
      - host: brdnc.co.kr
        paths:
      - host: www.brdnc.co.kr
    tls:
      - hosts:
          - brdnc.co.kr
          - www.brdnc.co.kr
