# Default values for Rebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx:
  ingress:
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: web-devbox-kr-cert
        hosts:
          - ""
