# Default values for Rebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  appMode: dev

mariadb:
  replicaCount: 2

nginx:
  image:
    repository: dokube/nginx
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 1
  
  service:
    port: 8881

web:
  imageConfigMaps:
    djangoSettingsModule: _config.settings.local
