# Default values for Rebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  appMode: dev

nginx:
  replicaCount: 1
  
  service:
    port: 8881
  
  ingress:
    hosts:
    - host: "host-path" # Host address
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: web-dev-kr-tls
      hosts:
      - "host-path" # Host address
