apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-config
data:
  MYSQL_DATABASE: "{{ .Release.Name }}"
  MYSQL_USER: "{{ .Release.Name }}"
  TZ: "{{ .Values.timeZone }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-replica-cm
data:
  primary.cnf: |
    [mariadb]
    log-bin                     # enable binary logging
    log-basename=rebs           # used to be independent of hostname changes (otherwise is in data/mysql)
    binlog_expire_logs_seconds=432000  # 5일(5*24*60*60 초) 동안 보관 후 삭제

  replica.cnf: |
    [mariadb]
    log-basename=rebs           # used to be independent of hostname changes (otherwise is in data/mysql)

  primary.sql: |
    GRANT REPLICATION REPLICA ON *.* TO 'rebs'@'%';

  secondary.sql: |
    # We have to know name of sts (`mariadb`) and service `mariadb-service` in advance as an FQDN.No need to use master_port
    CHANGE MASTER TO
    MASTER_HOST='mariadb-0.{{ .Values.global.dbServiceName }}.{{ .Release.Namespace }}.svc.cluster.local', # mariadb-0.<headless service name>.<namespace name>.svc.cluster.local
    MASTER_USER='{{ .Release.Name }}',
    MASTER_PASSWORD='{{ .Values.global.dbPassword }}',
    MASTER_CONNECT_RETRY=10;
