apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-config
data:
  MYSQL_DATABASE: "{{ .Release.Name }}"
  MYSQL_USER: "{{ .Release.Name }}"
  TZ: "{{ .Values.timeZone }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-replica-cm
data:
  primary.cnf: |
    [mariadb]
    log-bin                     # enable binary logging
    log-basename=rebs           # used to be independent of hostname changes (otherwise is in data/mysql)
    binlog_expire_logs_seconds=604800  # 7일(7*24*60*60 초) 동안 보관 후 삭제



  replica.cnf: |
    [mariadb]
    log-basename=rebs           # used to be independent of hostname changes (otherwise is in data/mysql)

  primary.sql: |
    CREATE USER '{{ .Release.Name }}'@'%';
    GRANT ALL PRIVILEGES ON *.* TO '{{ .Release.Name }}'@'%';
    CREATE DATABASE {{ .Release.Name }};

  slave-init.sh: |
    #!/bin/bash
    MASTER_STATUS=$(mariadb -h mariadb-0.{{ .Values.global.dbServiceName }}.{{ .Release.Namespace }}.svc.cluster.local \
    -uroot -p$MYSQL_ROOT_PASSWORD -e "SHOW MASTER STATUS\G")
    MASTER_LOG_FILE=$(echo "$MASTER_STATUS" | grep File: | awk '{print $2}')
    MASTER_LOG_POS=$(echo "$MASTER_STATUS" | grep Position: | awk '{print $2}')
    mariadb -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e "
        STOP SLAVE;
        CHANGE MASTER TO
            MASTER_HOST='mariadb-0.{{ .Values.global.dbServiceName }}.{{ .Release.Namespace }}.svc.cluster.local',
            MASTER_USER='{{ .Release.Name }}',
            MASTER_PASSWORD='{{ .Values.global.dbPassword }}',
            MASTER_LOG_FILE='$MASTER_LOG_FILE',
            MASTER_LOG_POS=$MASTER_LOG_POS,
            MASTER_CONNECT_RETRY=10;
        START SLAVE;
    "
