apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mariadb.fullname" . }}1-data-nfs-pv
spec:
  storageClassName: mysql-data
  capacity:
    storage: {{ .Values.volumes.dataPvStorage }}
  accessModes:
  {{- range .Values.volumes.dataAccessModes }}
    - {{ . }}
  {{- end }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/lib/jenkins/workspace/Rebs/volume/mysql-dev
    server: {{ .Values.volumes.nfsServerHost }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mariadb.fullname" . }}1-sql-nfs-pv
spec:
  storageClassName: backup-sql
  capacity:
    storage: {{ .Values.volumes.sqlPvStorage }}
  accessModes:
  {{- range .Values.volumes.sqlAccessModes }}
    - {{ . }}
  {{- end }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/lib/jenkins/workspace/Rebs/volume/sql
    server: {{ .Values.volumes.nfsServerHost }}
