apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb.fullname" . }}-data-{{ .Values.global.appMode }}-nfs-pvc
spec:
  storageClassName: mysql-data
  accessModes:
  {{- range .Values.volumes.dataAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.dataPvcStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb.fullname" . }}-sql-{{ .Values.global.appMode }}-nfs-pvc
spec:
  storageClassName: backup-sql
  accessModes:
  {{- range .Values.volumes.sqlAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.sqlPvcStorage }}
