apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  MYSQL_PASSWORD: c2VjcmV0
  MYSQL_ROOT_PASSWORD: c2VjcmV0
