apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-db-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ tpl .Values.global.dbPassword . | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ tpl .Values.global.dbPassword . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: mariadb-secret
type: Opaque
data:
  mariadb-root-password: c2VjcmV0 # echo -n 'secret' | base64
