name: DB_BACKUP

on:
  push:
  schedule:
    - cron: "0 2 * * 0"

jobs:
  backup:

    name: DB_BACKUP
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands from ci/cd server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}
          command: |
            kubectl exec -it -n prod-hrebs master-5c878f6b5f-pk8bm -- ls -al
