name: DB_BACKUP

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  backup:
    name: DB_BACKUP
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands from ci/cd server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}
          command: |
            db=$(kubectl get pod -n prod-hrebs | grep master | cut -d ' ' -f1)
            kubectl exec -it -n prod-hrebs $db -- bash
            pwd && ls -al
