name: DB_BACKUP

on:
  push:
  schedule:
    - cron: "0 2 * * 0"

jobs:
  backup:

    name: DB_BACKUP
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands from ci/cd server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}
          command: |
            DB=$(kubectl get pod -n dev-hrebs | grep master | cut -d ' ' -f1)
            kubectl exec -it -n prod-hrebs $DB -- ls -al /docker-entrypoint-initdb.d/
