name: Django_prod_action

on:
  push:
    paths:
      - "app/django/**"
      - ".github/workflows/django_prod.yml"
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# job은 사용자가 정한 플랫폼을 통해 steps 라는 일련의 과정을 실행.
# 여러 개의 job 을 사용할 수 있으며, 여러 개의 job 을 사용할 때는 서로 정보도 교환 가능.
# 각각 독립적으로도 실행 가능.
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # 레파지터리 체크 아웃
      - name: Check out source code
        uses: actions/checkout@v3

      # data to server copy transfer
      - name: Copy django, etc data to CI/CD server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}
          source: 'app/django'
          target: '/mnt/nfs/prod'

      # web pod --> django model migrations & collectstatic
      - name: django model migration & collectstatic
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          password: ${{ secrets.CICD_PASSWORD }}
          command: |
            web_pod=$(kubectl get pod -n prod-hrebs | grep web | cut -d ' ' -f1)
            kubectl exec -it -n prod-hrebs $web_pod -- cp _config/settings/local.py _config/settings/prod.py
#            kubectl exec -it -n prod-hrebs $web_pod -- sed -i 's/True/False/g' _config/settings/prod.py
            kubectl exec -it -n prod-hrebs $web_pod -- sed -i '2,6 s/*/${{ secrets.DOMAIN_NAME }}/g' _config/settings/prod.py
            kubectl exec -it -n prod-hrebs $web_pod -- sed -i '/CSRF_TRUSTED_ORIGINS/d' _config/settings/prod.py | sed '/^$/d'
            kubectl exec -it -n prod-hrebs $web_pod -- python manage.py makemigrations accounts book cash company contract document notice project rebs
            kubectl exec -it -n prod-hrebs $web_pod -- python manage.py migrate
            kubectl exec -it -n prod-hrebs $web_pod -- python manage.py collectstatic --no-input

      # slack --> notification
      - name: Send slack when failed
        if: ${{ failure() }}                    # 실패했을 때 실행
        uses: ./.github/actions/slack-notify    # 직접 '만든' Action이므로 uses 키워드를 이용해서 아래 경로를 입력해줍니다.
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: Send slack if completed
        if: ${{ success() }}                    # 성공할 때만 실행
        uses: ./.github/actions/slack-notify
        with:
          status: success   # status input은 받는 쪽에서 default 값을 정해놨기 때문에 success일 때만 전달.
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
