name: CI
on:
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Check th path and resource
        run: pwd; ls -al
      - name: Yarn build
        run: |
          cd app/vue
          yarn && yarn build
          cp ../django/static/dist/index.html ../django/templates/base-vue.html
          ls -alh ../django/templates
